[project]
name = "python-reddit-scraper"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Tadeas Fort", email = "business@tadeasfort.com" }]
dependencies = [
    "tqdm>=4.66.0",
    "camoufox>=0.4.0",
    "prompt-toolkit>=3.0.0",
    "typer>=0.15.0",
]
readme = "README.md"
requires-python = ">= 3.10"
license = { text = "GPL-3.0" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.rye]
managed = true
dev-dependencies = [
    "mkdocs-material>=9.6.0",
    "mkdocstrings[python]>=0.27.0",
]

[project.scripts]
download-reddit-media = "python_reddit_scraper.cli:app"
